#!/usr/bin/env bash

# basic ass install thing until i decide what i want longer term solution

# link
ln -srf bin ~/bin
ln -srf tmux/tmux.conf ~/.tmux.conf
ln -srf git/gitalias.txt ~/.gitalias.txt



# git config
git config --global include.path ~/.gitalias.txt
git config --global alias.l "ll -n15"

# tmux
if [ ! -e ~/.tmux/plugins ]; then
	echo "couldn't find tpm tmux plugin dir, creating"
	mkdir -p ~/.tmux/plugins/
fi

if [ ! -e ~/.tmux/plugins/tpm ]; then
	echo "couldn't find tpm plugin, cloning tpm"
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# aliases
