#!/usr/bin/env bash

# basic ass install thing until i decide what i want longer term solution

# make directories? maybe incomplete
mkdir -p ~/.config/kak/
mkdir -p ~/.config/fish/

# generallink
ln -srf bin ~/bin
ln -srf tmux/tmux.conf ~/.tmux.conf
ln -srf fish/config.fish ~/.config/fish/
# ln -srf git/gitalias.txt ~/.gitalias.txt
ln -srf git/myGitAliases.txt ~/.gitalias.txt
ln -srf helix ~/.config/
ln -srf starship/starship.toml ~/.config/starship.toml
ln -srf kak/kakrc ~/.config/kak/

# graphics/desktop things, some of which quite outdated
ln -srf wireplumber ~/.config/
ln -srf sway ~/.config/
ln -srf swaylock ~/.config/
ln -srf wlogout ~/.config/
ln -srf waybar ~/.config/
ln -srf polybar ~/.config/
ln -srf i3 ~/.config/
# interferes with cachy-os, disabled for now
# ln -srf alacritty ~/.config/

# git config
git config --global include.path ~/.gitalias.txt

# tmux
tmux/tmux.install

# fish
fish/install.fish


