" mappings

let mapleader=","
nnoremap <leader>l :ls<CR>
nnoremap <leader>b :ls<CR>:b
nnoremap <leader>w <C-w>
nnoremap <leader>n :set invnumber<CR>

" plugins

call plug#begin('~/vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ayu-theme/ayu-vim'

call plug#end()

" theme
let g:airline_theme='deus'

" truecolor with tmux/vim/alacritty
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
endif

set termguicolors
let ayucolor="mirage"
colorscheme ayu

" all tabs must die
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" who enabled it in the first place?
set paste

" highlight search term
set hlsearch

" line numbers on by default
set nu

" cya mouse
set mouse =


