" twig's vimrc
"
" enabling default:
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" vim-plug

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'ayu-theme/ayu-vim'
Plug 'fnune/base16-vim'

Plug 'preservim/nerdtree'

Plug 'vim-syntastic/syntastic'

" Plug 'ctrlpvim/ctrlp.vim'

" Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Plug  'pangloss/vim-javascript'

" Plug 'othree/yajs.vim'

" Plug 'sbdchd/neoformat'

Plug 'udalov/kotlin-vim'

call plug#end()

" theme
let g:airline_theme='deus'
" javascript lint

let g:syntastic_javascript_checkers=['eslint']
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" autostart NERDTREE
"autocmd vimenter * NERDTree

" truecolor with tmux/vim/alacritty
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
endif

" set termguicolors
" let ayucolor="mirage"
" colorscheme ayu

" mappings
let mapleader =","
nnoremap <leader>t :NERDTree<CR>
nnoremap <leader>l :ls<CR>
nnoremap <leader>b :ls<CR>:b
nnoremap <leader>w <C-w>
nnoremap <leader>n :set invnumber<CR>

" who enabled it in the first place?
set paste

" line numbers on by default
set nu

" highlight search terms
set hlsearch

" cya mouse
set mouse =

" all tabs must die
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4


