evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "occivink/kakoune-buffer-switcher"

plug "crizan/kak-rainbower"

#plug 'delapouite/kakoune-buffers' %{
#  map global normal ^ q
#  map global normal <a-^> Q
#  map global normal q b
#  map global normal Q B
#  map global normal <a-q> <a-b>
#  map global normal <a-Q> <a-B>
#  map global normal b ': enter-buffers-mode<ret>' -docstring 'buffers'
#  map global normal B ': enter-user-mode -lock buffers<ret>' -docstring 'buffers (lock)'
#}


set-option global tabstop 4

add-highlighter global/ number-lines

colorscheme gruvbox-dark
